apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-api.fullname" .}}-secrets
type: Opaque
data:
  DB_HOST: "{{ printf "%s-postgresql" .Release.Name | b64enc }}"
  DB_USER: "{{ .Values.goApiSettings.dbUser | default "" | b64enc }}"
  DB_PASSWORD: "{{ .Values.goApiSettings.dbPassword | default "" | b64enc }}"
  DB_NAME: "{{ .Values.goApiSettings.dbName | default "" | b64enc }}"